### ISSUE TITLE
Question about voltage measurement

### ISSUE THREAD

**Issue by beicnet** [PaulRB/Wemos-Weather-Station#2]
What is it represents?

`double battLevelNow = analogRead(BATT_LEVEL) / 209.66; // assumes external 180K resistor`

**`209.66`** Measured resistor value by multimeter or?

**Comment by PaulRB** [comment]
It's a value calculated to give a known output voltage in the above formula, compared to my (inexpensive) multimeter. You can adjust the value for you own circuit if required.

**Comment by beicnet** [comment]
Okay @PaulRB so how did you calculate it and by what formula any explanation?!

Thank you

**Comment by PaulRB** [comment]
I calculated it with basic School maths!

Connect a voltage to the analog pin (via the 180K resistor). Measure that voltage with your multimeter, let's say that's 3.27V for example. Take the raw analogRead() value, let's say that's 686. Divide one by the other, you get 209.66.
